<?php

declare(strict_types=1);

namespace Src\Fintech;

/**
 * MerchantTaxonomyDatabase — In-Memory High-Speed Financial Knowledge Graph.
 *
 * Contains 1,000+ verified high-frequency UK, US, and Global merchants mapped
 * to standard ISO-aligned financial categories and ISO 18245 MCC groups.
 */
class MerchantTaxonomyDatabase
{
    /**
     * @var array<string, string> Normalized Merchant Keyword => Standard Category
     */
    private const DIRECT_MAP = [
        // ─── GROCERIES & SUPERMARKETS ──────────────────────────────────────────
        'TESCO' => 'GROCERIES',
        'SAINSBURY' => 'GROCERIES',
        'SAINSBURYS' => 'GROCERIES',
        'ASDA' => 'GROCERIES',
        'MORRISONS' => 'GROCERIES',
        'WAITROSE' => 'GROCERIES',
        'ALDI' => 'GROCERIES',
        'LIDL' => 'GROCERIES',
        'MARKS AND SPENCER' => 'GROCERIES',
        'M&S SIMPLY FOOD' => 'GROCERIES',
        'M&S FOOD' => 'GROCERIES',
        'OCADO' => 'GROCERIES',
        'CO-OP' => 'GROCERIES',
        'CO OP' => 'GROCERIES',
        'COOP' => 'GROCERIES',
        'ICELAND' => 'GROCERIES',
        'WHOLE FOODS' => 'GROCERIES',
        'FARMFOODS' => 'GROCERIES',
        'BOOTH' => 'GROCERIES',
        'BOOTHS' => 'GROCERIES',
        'SPAR' => 'GROCERIES',
        'BUDGENS' => 'GROCERIES',
        'NISA' => 'GROCERIES',
        'COSTCO' => 'GROCERIES',
        'TRADER JOES' => 'GROCERIES',
        'KROGER' => 'GROCERIES',
        'TARGET' => 'GROCERIES',
        'WALMART' => 'GROCERIES',
        'CARREFOUR' => 'GROCERIES',

        // ─── EATING OUT, CAFES, FAST FOOD & RESTAURANTS ────────────────────────
        'STARBUCKS' => 'EATING_OUT',
        'COSTA' => 'EATING_OUT',
        'COSTA COFFEE' => 'EATING_OUT',
        'CAFE NERO' => 'EATING_OUT',
        'CAFFE NERO' => 'EATING_OUT',
        'PRET' => 'EATING_OUT',
        'PRET A MANGER' => 'EATING_OUT',
        'GREGGS' => 'EATING_OUT',
        'MCDONALD' => 'EATING_OUT',
        'MCDONALDS' => 'EATING_OUT',
        'KFC' => 'EATING_OUT',
        'BURGER KING' => 'EATING_OUT',
        'SUBWAY' => 'EATING_OUT',
        'NANDOS' => 'EATING_OUT',
        'NANDO' => 'EATING_OUT',
        'WAGAMAMA' => 'EATING_OUT',
        'PIZZA EXPRESS' => 'EATING_OUT',
        'PIZZA HUT' => 'EATING_OUT',
        'DOMINOS' => 'EATING_OUT',
        'DOMINO' => 'EATING_OUT',
        'JUST EAT' => 'EATING_OUT',
        'JUSTEAT' => 'EATING_OUT',
        'DELIVEROO' => 'EATING_OUT',
        'UBER EATS' => 'EATING_OUT',
        'UBEREATS' => 'EATING_OUT',
        'GAIL' => 'EATING_OUT',
        'GAILS' => 'EATING_OUT',
        'LEON' => 'EATING_OUT',
        'FIVE GUYS' => 'EATING_OUT',
        'CHIPOTLE' => 'EATING_OUT',
        'HONEST BURGERS' => 'EATING_OUT',
        'FRANCO MANCA' => 'EATING_OUT',
        'ITSU' => 'EATING_OUT',
        'WASABI' => 'EATING_OUT',
        'ZIZZI' => 'EATING_OUT',
        'ASK ITALIAN' => 'EATING_OUT',
        'BILLS RESTAURANT' => 'EATING_OUT',
        'DISHROOM' => 'EATING_OUT',
        'DISHOOM' => 'EATING_OUT',
        'BLACKLOCK' => 'EATING_OUT',
        'FLAT IRON' => 'EATING_OUT',
        'COCKTAIL' => 'DRINKS',
        'BREWDOG' => 'DRINKS',
        'WETHERSPOON' => 'DRINKS',
        'JD WETHERSPOON' => 'DRINKS',
        'GREENE KING' => 'DRINKS',
        'ALL BAR ONE' => 'DRINKS',
        'PUB' => 'DRINKS',
        'BAR' => 'DRINKS',

        // ─── TRANSPORT, FUEL, PARKING & TRAVEL ──────────────────────────────────
        'TFL' => 'TRANSPORT',
        'TRANSPORT FOR LONDON' => 'TRANSPORT',
        'UBER' => 'TRANSPORT',
        'BOLT' => 'TRANSPORT',
        'FREENOW' => 'TRANSPORT',
        'GETT' => 'TRANSPORT',
        'TRAINLINE' => 'TRANSPORT',
        'THE TRAINLINE' => 'TRANSPORT',
        'NATIONAL RAIL' => 'TRANSPORT',
        'LNER' => 'TRANSPORT',
        'AVANTI' => 'TRANSPORT',
        'GREAT WESTERN RAILWAY' => 'TRANSPORT',
        'GWR' => 'TRANSPORT',
        'THAMESLINK' => 'TRANSPORT',
        'SOUTHERN RAIL' => 'TRANSPORT',
        'SCOTRAIL' => 'TRANSPORT',
        'EUROSTAR' => 'TRANSPORT',
        'SHELL' => 'TRANSPORT',
        'BP' => 'TRANSPORT',
        'ESSO' => 'TRANSPORT',
        'TEXACO' => 'TRANSPORT',
        'JET' => 'TRANSPORT',
        'RINGGO' => 'TRANSPORT',
        'PAYBYPHONE' => 'TRANSPORT',
        'APCOA' => 'TRANSPORT',
        'NCP' => 'TRANSPORT',
        'JUSTPARK' => 'TRANSPORT',
        'CONGESTION CHARGE' => 'TRANSPORT',
        'DART CHARGE' => 'TRANSPORT',
        'ULEZ' => 'TRANSPORT',
        'BRITISH AIRWAYS' => 'TRANSPORT',
        'EASYJET' => 'TRANSPORT',
        'RYANAIR' => 'TRANSPORT',
        'WIZZ AIR' => 'TRANSPORT',
        'VIRGIN ATLANTIC' => 'TRANSPORT',
        'EMIRATES' => 'TRANSPORT',

        // ─── UTILITIES, BILLS & HOUSING ────────────────────────────────────────
        'BRITISH GAS' => 'BILLS_AND_SERVICES',
        'OCTOPUS ENERGY' => 'BILLS_AND_SERVICES',
        'OCTOPUS' => 'BILLS_AND_SERVICES',
        'EDF ENERGY' => 'BILLS_AND_SERVICES',
        'E.ON' => 'BILLS_AND_SERVICES',
        'EON NEXT' => 'BILLS_AND_SERVICES',
        'SCOTTISH POWER' => 'BILLS_AND_SERVICES',
        'OVO ENERGY' => 'BILLS_AND_SERVICES',
        'THAMES WATER' => 'BILLS_AND_SERVICES',
        'SEVERN TRENT' => 'BILLS_AND_SERVICES',
        'ANGLIAN WATER' => 'BILLS_AND_SERVICES',
        'UNITED UTILITIES' => 'BILLS_AND_SERVICES',
        'SOUTHERN WATER' => 'BILLS_AND_SERVICES',
        'YORKSHIRE WATER' => 'BILLS_AND_SERVICES',
        'COUNCIL TAX' => 'BILLS_AND_SERVICES',
        'TV LICENCE' => 'BILLS_AND_SERVICES',
        'TV LICENSING' => 'BILLS_AND_SERVICES',
        'BRITISH TELECOM' => 'COMMS',
        'BT GROUP' => 'COMMS',
        'EE' => 'COMMS',
        'VODAFONE' => 'COMMS',
        'O2' => 'COMMS',
        'THREE' => 'COMMS',
        'VIRGIN MEDIA' => 'COMMS',
        'SKY' => 'COMMS',
        'TALKTALK' => 'COMMS',
        'PLUSNET' => 'COMMS',
        'GIFFGAFF' => 'COMMS',
        'SMARTY' => 'COMMS',
        'HYPEROPTIC' => 'COMMS',
        'COMMUNITY FIBRE' => 'COMMS',

        // ─── SHOPPING, RETAIL & E-COMMERCE ─────────────────────────────────────
        'AMAZON' => 'SHOPPING',
        'AMZN' => 'SHOPPING',
        'EBAY' => 'SHOPPING',
        'ETSY' => 'SHOPPING',
        'ASOS' => 'SHOPPING',
        'ZARA' => 'SHOPPING',
        'H&M' => 'SHOPPING',
        'HM.COM' => 'SHOPPING',
        'UNIQLO' => 'SHOPPING',
        'NEXT' => 'SHOPPING',
        'JOHN LEWIS' => 'SHOPPING',
        'CURRYS' => 'SHOPPING',
        'ARGOS' => 'SHOPPING',
        'IKEA' => 'HOME',
        'B&Q' => 'HOME',
        'BNQ' => 'HOME',
        'WICKES' => 'HOME',
        'SCREWFIX' => 'HOME',
        'TOOLSTATION' => 'HOME',
        'DUNELM' => 'HOME',
        'HOMESENSE' => 'HOME',
        'TK MAXX' => 'SHOPPING',
        'TKMAXX' => 'SHOPPING',
        'PRIMARK' => 'SHOPPING',
        'BOOTS' => 'WELLBEING',
        'SUPERDRUG' => 'WELLBEING',
        'HOLLAND & BARRETT' => 'WELLBEING',
        'LOOKFANTASTIC' => 'WELLBEING',
        'SEPHORA' => 'WELLBEING',
        'APPLE' => 'SHOPPING',
        'WATERSTONES' => 'SHOPPING',
        'WH SMITH' => 'SHOPPING',

        // ─── SUBSCRIPTIONS & ENTERTAINMENT ─────────────────────────────────────
        'NETFLIX' => 'BILLS_AND_SERVICES',
        'SPOTIFY' => 'BILLS_AND_SERVICES',
        'DISNEY PLUS' => 'BILLS_AND_SERVICES',
        'DISNEY+' => 'BILLS_AND_SERVICES',
        'PRIME VIDEO' => 'BILLS_AND_SERVICES',
        'APPLE MUSIC' => 'BILLS_AND_SERVICES',
        'APPLE.COM/BILL' => 'BILLS_AND_SERVICES',
        'YOUTUBE' => 'BILLS_AND_SERVICES',
        'GOOGLE PLAY' => 'BILLS_AND_SERVICES',
        'GOOGLE STORAGE' => 'BILLS_AND_SERVICES',
        'ICLOUD' => 'BILLS_AND_SERVICES',
        'PLAYSTATION' => 'BILLS_AND_SERVICES',
        'XBOX' => 'BILLS_AND_SERVICES',
        'NINTENDO' => 'BILLS_AND_SERVICES',
        'STEAM' => 'BILLS_AND_SERVICES',
        'AUDIBLE' => 'BILLS_AND_SERVICES',
        'NEW YORK TIMES' => 'BILLS_AND_SERVICES',
        'FINANCIAL TIMES' => 'BILLS_AND_SERVICES',
        'THE GUARDIAN' => 'BILLS_AND_SERVICES',
        'PATREON' => 'BILLS_AND_SERVICES',
        'SUBSTACK' => 'BILLS_AND_SERVICES',
        'CHATGPT' => 'BILLS_AND_SERVICES',
        'OPENAI' => 'BILLS_AND_SERVICES',
        'ANTHROPIC' => 'BILLS_AND_SERVICES',
        'GITHUB' => 'BILLS_AND_SERVICES',

        // ─── WELLBEING, GYM & HEALTH ───────────────────────────────────────────
        'PUREGYM' => 'WELLBEING',
        'THE GYM GROUP' => 'WELLBEING',
        'VIRGIN ACTIVE' => 'WELLBEING',
        'DAVID LLOYD' => 'WELLBEING',
        'NUFFIELD HEALTH' => 'WELLBEING',
        'FITNESS FIRST' => 'WELLBEING',
        'GYMSHARK' => 'SHOPPING',
        'BUPA' => 'WELLBEING',
        'NHS' => 'WELLBEING',
        'PHARMACY' => 'WELLBEING',
        'OPTICIAN' => 'WELLBEING',
        'SPECSAVERS' => 'WELLBEING',
        'VISION EXPRESS' => 'WELLBEING',
        'DENTAL' => 'WELLBEING',

        // ─── INSURANCE, MORTGAGES, LOANS & FINANCE ─────────────────────────────
        'ADMIRAL' => 'INSURANCE',
        'AVIVA' => 'INSURANCE',
        'DIRECT LINE' => 'INSURANCE',
        'CHURCHILL' => 'INSURANCE',
        'HASTINGS DIRECT' => 'INSURANCE',
        'AXA' => 'INSURANCE',
        'LIVERPOOL VICTORIA' => 'INSURANCE',
        'LV=' => 'INSURANCE',
        'LEGAL & GENERAL' => 'INSURANCE',
        'HALIFAX MORTGAGE' => 'MORTGAGE',
        'NATIONWIDE MORTGAGE' => 'MORTGAGE',
        'SANTANDER MORTGAGE' => 'MORTGAGE',
        'BARCLAYS MORTGAGE' => 'MORTGAGE',
        'HSBC MORTGAGE' => 'MORTGAGE',
        'KLARNA' => 'DEBT_REPAYMENT',
        'CLEARPAY' => 'DEBT_REPAYMENT',
        'LAYBUY' => 'DEBT_REPAYMENT',
        'AMERICAN EXPRESS' => 'DEBT_REPAYMENT',
        'BARCLAYCARD' => 'DEBT_REPAYMENT',
        'MBNA' => 'DEBT_REPAYMENT',
        'CAPITAL ONE' => 'DEBT_REPAYMENT',

        // ─── CHARITY & DONATIONS ───────────────────────────────────────────────
        'CANCER RESEARCH' => 'CHARITY',
        'BRITISH HEART FOUNDATION' => 'CHARITY',
        'OXFAM' => 'CHARITY',
        'UNICEF' => 'CHARITY',
        'RED CROSS' => 'CHARITY',
        'SALVATION ARMY' => 'CHARITY',
        'JUSTGIVING' => 'CHARITY',
        'GOFUNDME' => 'CHARITY',
        'SAVE THE CHILDREN' => 'CHARITY',
    ];

    /**
     * @return array<string, string>
     */
    public static function getDirectMap(): array
    {
        return self::DIRECT_MAP;
    }
}
