version: 2
updates:
  # Enable version updates for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "modernman00"
    assignees:
      - "modernman00"
    commit-message:
      prefix: "composer"
      prefix-development: "composer-dev"
    labels:
      - "dependencies"
      - "composer"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "modernman00"
    assignees:
      - "modernman00"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
